version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - nginx_network

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 112233
      MYSQL_DATABASE: testdb
    networks:
      - mysql_network

networks:
  nginx_network:
    driver: bridge

  mysql_network:
    driver: bridge

